name: "Build interop container"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zig-libp2p
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#interop-container
      # Load this with docker load < result
      - uses: actions/upload-artifact@v2
        with:
          name: interop-container
          path: result
