name: Interoperability Testing
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run-multidim-interop:
    name: Run multidimensional interoperability tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t zig-libp2p-head -f interop/Dockerfile --build-arg CACHIX_AUTH_TOKEN=${{ secrets.CACHIX_AUTH_TOKEN }} .
      - uses: libp2p/test-plans/.github/actions/run-interop-ping-test@marco/read-only-cache-support
        with:
          test-filter: zig-libp2p-head
          extra-versions: ${{ github.workspace }}/interop/ping-version.json
