name: "Run tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
    env:
      COVERAGES: ""
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zig-libp2p
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Restore Zig Cache
        id: zig-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            zig-cache
          key: ${{ runner.os }}-zig-cache
      - run: nix develop . -c zig build crypto-tests
      - run: ./zig-out/bin/crypto-tests
      - run: nix develop . -c zig build interop-test
      - run: ./zig-out/bin/interop-test
      - name: Save zig cache
        id: zig-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            zig-cache
          key: ${{ steps.zig-cache-restore.outputs.cache-primary-key }}
