name: "Run tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
    env:
      COVERAGES: ""
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zig-libp2p
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop . -c zig build crypto-tests
      - run: ./zig-out/bin/crypto-tests
      - run: nix develop . -c zig build interop-test
      - run: ./zig-out/bin/interop-test
